### ISSUE TITLE
No tabs (?) 

### ISSUE THREAD

**Issue by Sowd0404** [scottmckendry/Windots#12]
In the previews you showcase your terminal having tabs of some sort 

![image](https://github.com/user-attachments/assets/6b12cb49-a286-4162-8a18-299497f98e8b)
but if I open my terminal, do ctrl + shift + p and run the new tab command, it does not showcase this bar at the top

i may be misunderstanding what it is

**Comment by scottmckendry** [comment]
You're correct, these are tabs. However, the screenshots were taken in Wezterm, not windows terminal.

See the config file here:

https://github.com/scottmckendry/Windots/blob/66b478c81f992b46b0b6563a45ba5d19bf1e85b6/wezterm/wezterm.lua#L35

**Comment by Sowd0404** [comment]
Thank you so much!
