### ISSUE TITLE
Can't run Setup.ps1

### ISSUE THREAD

**Issue by rashedazzam** [scottmckendry/Windots#4]
Hello, I installed winget and powershell 7. I opened powershell and typed:
`git clone https://github.com/scottmckendry/Windots/issues/new`
I then entered the Windots file and tried running:
`Setup.ps1`
Nothing happened. So I opened it from the file manager and right clicked > run with powershell.
Also nothing happened
What am I missing??

Thanks

**Comment by scottmckendry** [comment]
Try opening PowerShell 7 (As admin - won't work without elevated privileges), navigating to the cloned repo and running `.\Setup.ps1` from there. I suspect it may be falling back to Windows Powershell.

You may also need to set your [execution policy ](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.3) to allow the script to run.

**Comment by rashedazzam** [comment]
Okay, it worked after I edited my execution policy.
But when I run the `nvim` command, I get the following:
nvim : The term 'nvim' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.

Edit: Thank you for the quick reply! Really appreciate it

**Comment by scottmckendry** [comment]
Chocolately should automatically add nvim to your system path so that's unexpected. If you reopen PowerShell do you get the same error?

If that doesn't work, the instructions [here](https://docs.chocolatey.org/en-us/troubleshooting#my-path-is-not-getting-updated) may help.

**Comment by rashedazzam** [comment]
Oh, I apologise lol, When I closed it it started working normally. But my PC is running very slow, is this normal? Another question: how can I return my terminal to normal state (with tabs and all)? Thnx in advance (:

**Comment by scottmckendry** [comment]
You can reset Windows Terminal to default settings by deleting `./windowsterminal/settings.json` from the cloned repo. Or if you only want the status bar back, you can just delete line 34 from the same file (`"launchMode": "focus"`).
 
 I'd also strongly suggest updating the `.gitconfig` file, unless you want my name against your commits ;)
