### ISSUE TITLE
Borders!

### ISSUE THREAD

**Issue by AxewBoTX** [scottmckendry/Windots#5]
I am not really good at navigating in code bases and stuff.
But I am really really really into the borders of the terminal in the screenshot.
I can't figure out how that is happening, how did you remove all the borders of Window's terminal? 
Is it a plugin type thing? Tell me please how to do it?
Thanks

**Comment by scottmckendry** [comment]
It's Windows Terminal's [Focus Mode](https://learn.microsoft.com/en-us/windows/terminal/tips-and-tricks#focus-mode)
