### ISSUE TITLE
powershell format error

### ISSUE THREAD

**Issue by ryannewcomer** [scottmckendry/Windots#8]
this is the output form :ConformInfo

![image](https://github.com/scottmckendry/Windots/assets/88273136/cbf5085b-fa4b-4ce4-9821-cc796bd4af96)

how to fix this?
i have not change the config.
i am on windows 11

**Comment by scottmckendry** [comment]
Thanks for raising!
`Install-Module PSScriptAnalyzer` should fix it. I'll make sure to include this in the setup script so it's included in future.

**Comment by ryannewcomer** [comment]
thanks! that work!
